practice-app/models/word.js
=> added Word model

practice-app/libs/create-exercise.js, practice-app/libs/getDatafromOxfordApi.js, practice-app/libs/getDatafromWikiData.js, practice-app/package-lock.json, practice-app/package.json
Wikidata api and oxford api work together now. Printing bugs are fixed.
=> Merge apis

practice-app/app.js
Json format for connection between frontend backend
=> result json example for backend

practice-app/app.js, practice-app/frontend/public/index.html, practice-app/libs/create-exercise.js
Backend and Frontend connected.
=> Integration

practice-app/app.js, practice-app/frontend/src/App.js, practice-app/libs/create-exercise.js, practice-app/package-lock.json, practice-app/package.json, practice-app/test/test.js
I have randomized questions and answers from objects of given class. On the other hand, number of question and number of options per question identities are now given as parameter. If other sides of app rearranged, we can add more or less questions and options per questions.
=> Randomize create exercise and test

practice-app/frontend/package-lock.json, practice-app/frontend/src/ResultPage/ResultPage.js, practice-app/libs/checkExercise.js, practice-app/package-lock.json, practice-app/package.json, practice-app/test/test_for_checkExercise.js
I added informative feedback section to the result page that gives the results to the user whether it is correct or not. And, if the answer is wrong, then we give the correct result to the user. In order to handle that, I made some changings on checkExercise.js and ResultPage.js. In addition to that, I also wrote a unit test for checkExercise() and getExerciseAnswers() functions using Mocha.
=> Give informative feedback after exercise

practice-app/libs/checkExercise.js, practice-app/test/testGenerateRenderedArray.js
I added tests for checking the data that comes from wikidata
=> added tests for genereateRenderedArray() function

languageLearning/.idea/misc.xml, languageLearning/app/src/main/AndroidManifest.xml, languageLearning/app/src/main/java/com/example/languageLearning/LoginActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/MyApplication.java, languageLearning/app/src/main/java/com/example/languageLearning/RegisterActivity.java
Closes #119 
I seem to have misnamed the branch. Sorry.
=> Android issue 119 - Creating an Application subclass

languageLearning/app/src/main/java/com/example/languageLearning/LoginActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/MainMenuActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/RegisterActivity.java
=> Fixed token format

languageLearning/app/src/main/java/com/example/languageLearning/Exercise.java, languageLearning/app/src/main/java/com/example/languageLearning/LoginActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/MyApplication.java, languageLearning/app/src/main/java/com/example/languageLearning/ProfExamActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/Question.java, languageLearning/app/src/main/java/com/example/languageLearning/RegisterActivity.java
=> Issue 207 - Updated the server address and API endpoint paths

backend/api/test/test_message.py, backend/api/views/message.py
=> test cases of message added.

languageLearning/app/build.gradle, languageLearning/app/src/main/AndroidManifest.xml, languageLearning/app/src/main/java/com/example/languageLearning/Exercise.java, languageLearning/app/src/main/java/com/example/languageLearning/ExerciseActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/ExerciseActivityTestActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/LoginActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/MyApplication.java, languageLearning/app/src/main/java/com/example/languageLearning/ProfExamActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/Question.java, languageLearning/app/src/main/java/com/example/languageLearning/RegisterActivity.java, languageLearning/app/src/main/res/drawable/ic_chevron_left_black_24dp.xml, languageLearning/app/src/main/res/drawable/ic_chevron_right_black_24dp.xml, languageLearning/app/src/main/res/layout/activity_exercise.xml
=> Android issue197 exercise

languageLearning/app/build.gradle, languageLearning/app/src/main/AndroidManifest.xml, languageLearning/app/src/main/java/com/example/languageLearning/Exercise.java, languageLearning/app/src/main/java/com/example/languageLearning/ExerciseActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/ExerciseActivityTestActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/MyApplication.java, languageLearning/app/src/main/java/com/example/languageLearning/ProfExamActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/Question.java, languageLearning/app/src/main/res/drawable/ic_chevron_left_black_24dp.xml, languageLearning/app/src/main/res/drawable/ic_chevron_right_black_24dp.xml, languageLearning/app/src/main/res/layout/activity_exercise.xml
=> Android issue216

languageLearning/app/src/main/java/com/example/languageLearning/ExerciseActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/ExerciseResultOverviewActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/MyApplication.java, languageLearning/app/src/main/java/com/example/languageLearning/ProfExamActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/Question.java, languageLearning/app/src/main/res/layout/activity_exercise_result_overview.xml
=> Android issue218

backend/api/filters/__init__.py, backend/api/filters/annotation.py, backend/api/views/annotation.py
#229 #228 issues are completed in this branch
=> annotation source filter added and retrieve is removed

languageLearning/app/src/main/java/com/example/languageLearning/ProfilePage.java
Backend connection is established for profile page in this PR.
=> Android issue193 profile conn

languageLearning/app/src/main/AndroidManifest.xml, languageLearning/app/src/main/java/com/example/languageLearning/Essay.java, languageLearning/app/src/main/java/com/example/languageLearning/ImageEssayDetailActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/NewEssayActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/SelectEssayReviewerActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/TextEssayDetailActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/UploadEssayActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/UserProfile.java, languageLearning/app/src/main/java/com/example/languageLearning/WriteNewEssayActivity.java, languageLearning/app/src/main/res/layout/activity_image_essay_detail.xml, languageLearning/app/src/main/res/layout/activity_select_essay_reviewer.xml, languageLearning/app/src/main/res/layout/activity_text_essay_detail.xml, languageLearning/app/src/main/res/layout/essay_reviewer_list_item.xml
=> Android issue259 essay rejection

languageLearning/app/src/main/AndroidManifest.xml, languageLearning/app/src/main/java/com/example/languageLearning/NewEssayActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/SelectEssayReviewerActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/UploadEssayActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/UserProfile.java, languageLearning/app/src/main/java/com/example/languageLearning/WriteNewEssayActivity.java, languageLearning/app/src/main/res/layout/activity_select_essay_reviewer.xml, languageLearning/app/src/main/res/layout/essay_reviewer_list_item.xml
=> Android issue254 essay reviewer

backend/api/admin.py, backend/api/models/question.py, backend/api/serializers/question.py, backend/api/urls.py, backend/api/views/exercise.py
alternative solutions for #250
=> alternative listening to base64

languageLearning/app/src/main/java/com/example/languageLearning/MainMenuActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/RegisterActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/SearchActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/SearchResultActivity.java, languageLearning/app/src/main/res/drawable/search_button.xml, languageLearning/app/src/main/res/layout/activity_main_menu.xml, languageLearning/app/src/main/res/values/strings.xml
**In This PR :**
- **Main Menu Connection of the Search Activity has been established**
- **Search Activity Typos has been fixed**
- **Search Activity & Search Result Activity code cleanup from unnecessary logs and comments**
- **Search Activity Bug when user does not select any language fixed**
- **Issue 264 Registration bug when no language selected is fixed**
More information can be found in commit history.
Regards
=> Android issue247 main menu connection

languageLearning/app/src/main/java/com/example/languageLearning/ImageEssayDetailActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/MyApplication.java, languageLearning/app/src/main/java/com/example/languageLearning/NewEssayActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/UploadEssayActivity.java
=> The code now correctly converts ratios by 100

languageLearning/app/src/main/java/com/example/languageLearning/UploadEssayActivity.java
=> Uploading essays from content providers is now supported

languageLearning/app/src/main/java/com/example/languageLearning/RegisterActivity.java
RegisterActivity now sends native_language to backend correctly.
Solves issue #287.
=> RegisterActivity now saves native language as all lowercase

languageLearning/app/src/main/java/com/example/languageLearning/ProfilePageActivity.java, languageLearning/app/src/main/res/layout/activity_profile_page.xml
=> Enhancements to the profile page

languageLearning/app/src/main/AndroidManifest.xml, languageLearning/app/src/main/java/com/example/languageLearning/EssayAdapter.java, languageLearning/app/src/main/java/com/example/languageLearning/MainMenuActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/UserAdapter.java, languageLearning/app/src/main/java/com/example/languageLearning/UserSearchActivity.java, languageLearning/app/src/main/res/layout/activity_search.xml, languageLearning/app/src/main/res/layout/activity_user_search.xml, languageLearning/app/src/main/res/layout/search_type_popup.xml, languageLearning/app/src/main/res/layout/user_element.xml, languageLearning/app/src/main/res/values/strings.xml
Search button in MainMenuActivity now opens popup and lets user select one of two search types, exercise or user.
UserSearchActivity now gets users from backend and displays them. After a search, clicking on "Language" text will reveal language selection options. Also clicking on user will direct app to that user's profile.
This pull request solves #282.
=> Android issue282 user search

frontend/src/containers/recommendation/index.js, frontend/src/containers/writingUpload/index.js
Recommended users are listed on a card.
Pop-up page to choose a recommended user is scrollable now.
=> recommendation page design

languageLearning/app/src/main/java/com/example/languageLearning/MyApplication.java
=> initiateAPICall now checks if error.getMessage() is null

languageLearning/app/src/main/java/com/example/languageLearning/TextEssayDetailActivity.java
=> Issue #299

languageLearning/app/build.gradle, languageLearning/app/src/main/java/com/example/languageLearning/AnnotationDialogHelper.java, languageLearning/app/src/main/java/com/example/languageLearning/ImageEssayDetailActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/MyApplication.java, languageLearning/app/src/main/java/com/example/languageLearning/TextEssayDetailActivity.java, languageLearning/app/src/main/res/layout/activity_image_essay_detail_loaded.xml, languageLearning/app/src/main/res/layout/activity_text_essay_detail_loaded.xml, languageLearning/build.gradle, languageLearning/photoview/.gitignore, languageLearning/photoview/build.gradle, languageLearning/photoview/src/main/AndroidManifest.xml, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/Compat.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/CustomGestureDetector.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/OnGestureListener.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/OnMatrixChangedListener.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/OnOutsidePhotoTapListener.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/OnPhotoTapListener.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/OnScaleChangedListener.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/OnSingleFlingListener.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/OnViewDragListener.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/OnViewTapListener.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/PhotoView.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/PhotoViewAttacher.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/Util.java, languageLearning/settings.gradle
Clicking on annotations now pop up a dialog, not a toast message.
=> Android issue313 annotation dialog

languageLearning/app/build.gradle, languageLearning/app/src/main/java/com/example/languageLearning/ImageEssayDetailActivity.java, languageLearning/app/src/main/res/layout/activity_image_essay_detail_loaded.xml, languageLearning/build.gradle, languageLearning/photoview/.gitignore, languageLearning/photoview/build.gradle, languageLearning/photoview/src/main/AndroidManifest.xml, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/Compat.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/CustomGestureDetector.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/OnGestureListener.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/OnMatrixChangedListener.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/OnOutsidePhotoTapListener.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/OnPhotoTapListener.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/OnScaleChangedListener.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/OnSingleFlingListener.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/OnViewDragListener.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/OnViewTapListener.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/PhotoView.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/PhotoViewAttacher.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/Util.java, languageLearning/settings.gradle
Image essays can now be zoomed by pinch, thanks to an awesome library from chrisbanes
=> Android issue313 image essay zoom

languageLearning/app/build.gradle, languageLearning/app/src/main/java/com/example/languageLearning/ImageEssayDetailActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/TextEssayDetailActivity.java, languageLearning/app/src/main/res/layout/activity_image_essay_detail_loaded.xml, languageLearning/app/src/main/res/layout/activity_text_essay_detail_loaded.xml, languageLearning/build.gradle, languageLearning/photoview/.gitignore, languageLearning/photoview/build.gradle, languageLearning/photoview/src/main/AndroidManifest.xml, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/Compat.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/CustomGestureDetector.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/OnGestureListener.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/OnMatrixChangedListener.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/OnOutsidePhotoTapListener.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/OnPhotoTapListener.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/OnScaleChangedListener.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/OnSingleFlingListener.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/OnViewDragListener.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/OnViewTapListener.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/PhotoView.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/PhotoViewAttacher.java, languageLearning/photoview/src/main/java/com/github/chrisbanes/photoview/Util.java, languageLearning/settings.gradle
Improvements to the text essay page
The essays are now shown bigger and are scrollable
=> Android issue313 text essay gui

frontend/src/containers/app/index.js, frontend/src/containers/app/styles.css
A navigation bar to the left of each page is created, chat link is not added since the page is not created yet.
=> Frontend navigation bar

languageLearning/app/src/main/java/com/example/languageLearning/UserAdapter.java, languageLearning/app/src/main/res/layout/user_element.xml
User search result elements now contains a profile icon to make it more understandable that when clicked as suggested at #293.
=> User search result design improvement

languageLearning/app/src/main/java/com/example/languageLearning/ExerciseActivityTestActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/MaxHeightScrollView.java, languageLearning/app/src/main/res/layout/activity_exercise.xml, languageLearning/app/src/main/res/values/attrs.xml
=> Android issue341 reading scroll

languageLearning/app/src/main/java/com/example/languageLearning/ChatLiveScreenActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/ExerciseActivityTestActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/MaxHeightScrollView.java, languageLearning/app/src/main/res/layout/activity_exercise.xml, languageLearning/app/src/main/res/values/attrs.xml
=> Android issue346 chat stop poll

languageLearning/app/src/main/java/com/example/languageLearning/ChatLiveScreenActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/ChatMessage.java, languageLearning/app/src/main/java/com/example/languageLearning/Essay.java, languageLearning/app/src/main/java/com/example/languageLearning/EssayAdapter.java, languageLearning/app/src/main/java/com/example/languageLearning/ExerciseActivityTestActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/MaxHeightScrollView.java, languageLearning/app/src/main/res/layout/activity_exercise.xml, languageLearning/app/src/main/res/layout/essay_element.xml, languageLearning/app/src/main/res/values/attrs.xml
=> Android issue344 show essay date

languageLearning/app/src/main/java/com/example/languageLearning/ChatLiveScreenActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/ChatMessage.java, languageLearning/app/src/main/java/com/example/languageLearning/Essay.java, languageLearning/app/src/main/java/com/example/languageLearning/EssayAdapter.java, languageLearning/app/src/main/java/com/example/languageLearning/Exercise.java, languageLearning/app/src/main/java/com/example/languageLearning/ExerciseActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/ExerciseActivityTestActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/ExerciseResultOverviewActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/MainMenuActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/MaxHeightScrollView.java, languageLearning/app/src/main/res/layout/activity_exercise.xml, languageLearning/app/src/main/res/layout/essay_element.xml, languageLearning/app/src/main/res/values/attrs.xml
=> Android issue350 use exercise type

languageLearning/app/build.gradle, languageLearning/app/src/main/java/com/example/languageLearning/ChatLiveScreenActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/ChatMessage.java, languageLearning/app/src/main/java/com/example/languageLearning/Essay.java, languageLearning/app/src/main/java/com/example/languageLearning/EssayAdapter.java, languageLearning/app/src/main/java/com/example/languageLearning/Exercise.java, languageLearning/app/src/main/java/com/example/languageLearning/ExerciseActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/ExerciseActivityTestActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/ExerciseResultOverviewActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/ListeningQuestionSuggestionActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/MainMenuActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/MaxHeightScrollView.java, languageLearning/app/src/main/java/com/example/languageLearning/MyApplication.java, languageLearning/app/src/main/java/com/example/languageLearning/UploadEssayActivity.java, languageLearning/app/src/main/res/layout/activity_exercise.xml, languageLearning/app/src/main/res/layout/essay_element.xml, languageLearning/app/src/main/res/values/attrs.xml
=> Android issue354 android 7

languageLearning/app/build.gradle, languageLearning/app/src/main/java/com/example/languageLearning/ChatLiveScreenActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/ChatMessage.java, languageLearning/app/src/main/java/com/example/languageLearning/Essay.java, languageLearning/app/src/main/java/com/example/languageLearning/EssayAdapter.java, languageLearning/app/src/main/java/com/example/languageLearning/Exercise.java, languageLearning/app/src/main/java/com/example/languageLearning/ExerciseActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/ExerciseActivityTestActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/ExerciseResultOverviewActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/ListEssaysActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/ListeningQuestionSuggestionActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/MainMenuActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/MaxHeightScrollView.java, languageLearning/app/src/main/java/com/example/languageLearning/MyApplication.java, languageLearning/app/src/main/java/com/example/languageLearning/UploadEssayActivity.java, languageLearning/app/src/main/res/layout/activity_exercise.xml, languageLearning/app/src/main/res/layout/essay_element.xml, languageLearning/app/src/main/res/values/attrs.xml
=> Android issue356 sort essays

languageLearning/app/build.gradle, languageLearning/app/src/main/java/com/example/languageLearning/ChatLiveScreenActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/ChatMessage.java, languageLearning/app/src/main/java/com/example/languageLearning/Essay.java, languageLearning/app/src/main/java/com/example/languageLearning/EssayAdapter.java, languageLearning/app/src/main/java/com/example/languageLearning/Exercise.java, languageLearning/app/src/main/java/com/example/languageLearning/ExerciseActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/ExerciseActivityTestActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/ExerciseResultOverviewActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/ListEssaysActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/ListEssaysTabbedFragment.java, languageLearning/app/src/main/java/com/example/languageLearning/ListeningQuestionSuggestionActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/MainMenuActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/MaxHeightScrollView.java, languageLearning/app/src/main/java/com/example/languageLearning/MyApplication.java, languageLearning/app/src/main/java/com/example/languageLearning/UploadEssayActivity.java, languageLearning/app/src/main/res/layout/activity_exercise.xml, languageLearning/app/src/main/res/layout/activity_list_essays.xml, languageLearning/app/src/main/res/layout/essay_element.xml, languageLearning/app/src/main/res/layout/list_essays_tab.xml, languageLearning/app/src/main/res/values/attrs.xml
=> Android issue360 seperate essays

languageLearning/app/src/main/java/com/example/languageLearning/LoginActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/MyApplication.java
=> Increased request timeout to 10 seconds

languageLearning/app/src/main/java/com/example/languageLearning/LoginActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/MyApplication.java, languageLearning/app/src/main/res/layout/left_chat_bubble.xml, languageLearning/app/src/main/res/layout/right_chat_bubble.xml
=> Android issue370 chat color

languageLearning/app/src/main/java/com/example/languageLearning/AppProgress.java, languageLearning/app/src/main/java/com/example/languageLearning/AppProgressResult.java, languageLearning/app/src/main/java/com/example/languageLearning/MyApplication.java, languageLearning/app/src/main/res/layout/activity_app_progress_resullt.xml
This PR includes,
+App Progress Bar 
+Changed Server IP
=> Android server issue

languageLearning/app/src/main/java/com/example/languageLearning/MyApplication.java, languageLearning/app/src/main/java/com/example/languageLearning/SearchActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/SearchResultActivity.java, languageLearning/app/src/main/res/layout/row.xml
This PR includes some Bug Fixes and feature improvements like better GUI for Search Exercise mentioned in the issue 343
=> Android issue343 search improvements

languageLearning/app/src/main/java/com/example/languageLearning/BridgeActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/LoginActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/MainMenuActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/ProfResultActivity.java, languageLearning/app/src/main/java/com/example/languageLearning/RegisterActivity.java, languageLearning/app/src/main/res/layout/activity_bridge.xml
=> Android issue280 choose language login
